# Generated by Django 5.2.8 on 2025-11-07 12:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('agent', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_size', models.FloatField(blank=True, null=True)),
                ('construction_size', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('price_amount', models.FloatField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('operation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('title_image_full', models.URLField(blank=True, null=True)),
                ('title_image_thumb', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sector_id', models.IntegerField()),
                ('type_id', models.IntegerField()),
                ('settlement', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('corridor', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('area_sqm', models.FloatField(blank=True, null=True)),
                ('price_sqm_rent', models.FloatField(blank=True, null=True)),
                ('price_total_rent', models.FloatField(blank=True, null=True)),
                ('price_sqm_sale', models.FloatField(blank=True, null=True)),
                ('price_total_sale', models.FloatField(blank=True, null=True)),
                ('maintenance_cost', models.FloatField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, max_length=50, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
