# Generated by Django 5.2.8 on 2025-11-06 23:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('agent', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('lot_size', models.FloatField(blank=True, null=True)),
                ('construction_size', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.FloatField(blank=True, null=True)),
                ('bedrooms', models.FloatField(blank=True, null=True)),
                ('parking_spaces', models.IntegerField(blank=True, null=True)),
                ('price_amount', models.FloatField(blank=True, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=10, null=True)),
                ('operation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('title_image_full', models.URLField(blank=True, null=True)),
                ('title_image_thumb', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
